<?php

namespace Troiswa\BackBundle\Tests\Repository;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepositoryTest extends KernelTestCase
{

    public function setUp()
    {
        self::bootKernel();
        $this->em = static::$kernel->getContainer()
            ->get('doctrine')
            ->getManager()
        ;
    }

    // Return createQueryBuilder beacause use in FormType
    public function testfindTitleOrderPositionForForm()
    {
        $categories = $this->em
            ->getRepository('TroiswaBackBundle:Category')
            ->findTitleOrderPositionForForm();


        $this->assertCount(2, $categories->getQuery()->getResult());
    }

    protected function tearDown()
    {
        parent::tearDown();
        $this->em->close();
    }
}