<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findTitleOrderPosition()
    {
        $query = $this->createQueryBuilder('cat');
        //die(var_dump($query->getQuery()));
        return $query->getQuery()->getResult();
    }
}
