troiswa_back_coupon:
    resource: "@TroiswaBackBundle/Resources/config/routing/coupon.yml"
    prefix:   /coupon

troiswa_back_cart_resource:
    resource: "@TroiswaBackBundle/Resources/config/routing/cart.yml"
    prefix:   /cart


troiswa_back_resource_user:
    resource: "@TroiswaBackBundle/Resources/config/routing/user.yml"
    prefix:   /user

troiswa_back_resource_category:
    resource: "@TroiswaBackBundle/Resources/config/routing/category.yml"
    prefix:   /category

troiswa_back_resource_product:
    resource: "@TroiswaBackBundle/Resources/config/routing/product.yml"
    prefix:   /product

troiswa_back_admin:
    path:     /
    defaults: { _controller: TroiswaBackBundle:Main:index }


troiswa_back_privacy:
    path: /privacy
    defaults:
      _controller: FrameworkBundle:Template:template
      template: 'TroiswaBackBundle:Main:index.html.twig'


troiswa_back_contact:
    path:     /contact
    defaults: { _controller: TroiswaBackBundle:Main:contact }


troiswa_back_login:
    pattern:   /login
    defaults:  { _controller: TroiswaBackBundle:Security:login }

troiswa_back_login_check:
    pattern:   /login_check

troiswa_back_logout:
    pattern:   /logout