services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    troiswa.form.type.tel:
      class: Troiswa\BackBundle\Form\Type\TelType
      tags:
        - { name: form.type, alias: tel }
