<?php

namespace Troiswa\BackBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCouponRepository extends EntityRepository
{
    public function getALlCouponFormType()
    {
        // Retourne simplement le queryBuilder car utiliser dans un formType
        return $this->getEntityManager()->createQueryBuilder()
                ->select('uc, coup')
                ->from('TroiswaBackBundle:Coupon', 'coup')
                ->leftJoin('coup.usercoupon', 'uc');
    }
}
